apiVersion: apps/v1
kind: Deployment
metadata:
    name: audieyes-deployment
    labels:
        app: audieyes
spec:
    replicas: 3
    selector:
        matchLabels:
            app: audieyes
    template:
        metadata:
            labels:
                app: audieyes
        spec:
            containers:
                - name: audieyes
                  image: ayoubmaimmadi/blip-image-captioning-api
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  resources:
                      requests:
                          memory: '64Mi'
                          cpu: '250m'
                      limits:
                          memory: '128Mi'
                          cpu: '500m'
