apiVersion: v1
kind: Service
metadata:
    name: audieyes-service
    annotations:
        service.beta.kubernetes.io/linode-loadbalancer-throttle: '4'
    labels:
        app: audieyes-service
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: audieyes
    sessionAffinity: None
