apiVersion: v1
kind: Service
metadata:
    name: evidently-service
    labels:
        app: evidently
spec:
    type: ClusterIP
    ports:
        - port: 5000
          targetPort: 5000
    selector:
        app: evidently
