version: '3.8'

services:
    image_captioning_api:
        image: blip-image-captioning-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - NAME=ImageCaptioning
        restart: unless-stopped
