version: '3.8'
services:
    web:
        build: .
        container_name: image_captioning_api
        ports:
            - '5000:5000'
        volumes:
            - .:/app
        environment:
            - NAME=World
