version: '3.8'

services:
    image_captioning_api:
        image: blip-image-captioning-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - NAME=ImageCaptioning
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mongo
        restart: always
        secrets:
            - db-password
        volumes:
            - db-data:/data/db
        environment:
            - MONGO_INITDB_DATABASE=example
            - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db-password
        expose:
            - 27017
        healthcheck:
            test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db-data:

secrets:
    db-password:
        file: db/password.txt
